title: Damage Down
description: Materia DC Guides, Macros and other raid resources.
theme: just-the-docs

url: https://DamageDownTools.github.io

aux_links:
  Template Repository: https://github.com/DamageDownTools/just-the-docs-template
