title: Damage Down
description: Materia DC Guides, Macros and other raid resources.
theme: just-the-docs

url: https://DamageDownTools.github.io

aux_links:
  Discord Server: https://discord.gg/zxYJ9HMdCZ

callouts:
  warning:
    title: Warning
    color: red