title: Damage Down
description: Materia DC Guides, Macros and other raid resources.
theme: just-the-docs

url: https://DamageDownTools.github.io

aux_links:
  Discord Server: https://discord.gg/zxYJ9HMdCZ

callouts:
  warning:
    title: Warning
    color: red

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/damagedown.png"
